apiVersion: apps/v1
kind: Deployment
metadata:
  name: self-healing-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: self-healing-web
  template:
    metadata:
      labels:
        app: self-healing-web
    spec:
      containers:
      - name: self-healing-web
        image: mikasa15/food-web:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
