apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: food-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Kavishreesiva/food-web.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
