apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.telegram: |
    token: $TELEGRAM_BOT_TOKEN

  template.app-health-status: |
    message: |
      🚨 Application {{.app.metadata.name}} is {{.app.status.health.status}}

  trigger.on-health-degraded: |
    - when: app.status.health.status == 'Degraded'
      send: [app-health-status]

  trigger.on-health-healthy: |
    - when: app.status.health.status == 'Healthy'
      send: [app-health-status]

---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
type: Opaque
stringData:
  TELEGRAM_BOT_TOKEN: <TELEGRAM_BOT_TOKEN>
  TELEGRAM_CHAT_ID: <TELEGRAM_CHAT_ID>
